<?php

use Dev\App\Application;

$this->appendScript('/js/view/main/home.mjs', true);
$router = Application::getInstance()->router;

dd($this);

$makeLink = function ($router, $routeName, $params = []) {
    $data = [
        '{url}' => $router->url($routeName, $params),
        '{label}' => $router->routeProperty($routeName, 'label', $params),
        '{title}' => $router->routeProperty($routeName, 'title', $params),
        '{class}' => $router->routeProperty($routeName, 'class', $params),
        '{target}' => $router->routeProperty($routeName, 'target', $params),
    ];

    $template = '<a class="link item {class}" title="{title}" href="{url}">{label}</a><br />';
    $link = strtr($template, $data);
    return $link;
}
?>

<h1>Home <small style="font-size: small"><?= $developer ?></small></h1>

<p>
    <input name='basic' value='tag1, tag2' autofocus><br />
</p>

<hr />
<p>
    <textarea name='mix'>[[{"id":101, "value":"cartman", "title":"Eric Cartman"}]] and [[kyle]] do not know [[{"value":"homer simpson", "readonly":true}]] because he's a relic.</textarea>
</p>

<hr />
<div class="links">
    <div class="items">
        <?=$makeLink($router, 'item', ['item' => 'panther'])?>
        <?=$makeLink($router, 'item', ['item' => 'tiger'])?>
    </div>
    <div>
        <a class="link" href="<?= $router->url('parse') ?>">Parse</a><br />
        <a class="link" href="<?= $router->url('develop') ?>">Develop</a><br />
        <a class="link" href="<?= $router->url('temperature') ?>">Temperature</a><br />
        <a class="link" href="<?= $router->url('user-list') ?>">REST User</a><br />
        <a class="link" href="<?= $router->url('user-get', ['id' => 1]) ?>">REST User: 1</a><br />
    </div>
    <div class="items">
        <?=$makeLink($router, 'home')?>
    </div>
</div>