<?php

use Dev\App\Application;

    $this->appendScript('/js/view/main/home.mjs', true);
    $router = Application::getInstance()->router;
?>

<h1>Home <small style="font-size: small"><?=$developer?></small></h1>

<p>
    <input name='basic' value='tag1, tag2' autofocus><br/>
</p>

<hr/>
<p>
<textarea name='mix'>[[{"id":101, "value":"cartman", "title":"Eric Cartman"}]] and [[kyle]] do not know [[{"value":"homer simpson", "readonly":true}]] because he's a relic.</textarea>
</p>

<hr/>

<a href="<?=$router->url('item', ['item' => 'panther'])?>">Item: Panther</a><br/>

<a href="<?=$router->url('item', ['item' => 'tiger'])?>">Item: Tiger</a><br/>

<a href="<?=$router->url('parse')?>">Parse</a><br/>

<a href="<?=$router->url('develop')?>">Develop</a><br/>

<a href="<?=$router->url('user-list')?>">REST User</a><br/>

<a href="<?=$router->url('user-get', ['id' => 1])?>">REST User: 1</a><br/>
