#!/usr/bin/env php
<?php
/**
 * Develop
 *
 * Tinkering development environment. Used to play with or try out stuff.
 *
 * PHP version 8.4
 *
 * @author Philip Michael Raab<philip@cathedral.co.za>
 * @package Develop\Tinker
 *
 * @license UNLICENSE
 * @license https://unlicense.org/UNLICENSE UNLICENSE
 *
 * @version $Id$
 * $Date$
 */

declare(strict_types= 1);

/**
 * git attribute tagger smudge
 *
 * version 3
 *
 * added @version tagging
 */
if (count($argv) > 1) { // we have some command line arguments to deal with
    if (file_exists("{$argv[1]}")) $code = file_get_contents("{$argv[1]}"); // the first argument is a valid file
    else if (file_exists(getcwd() . "/{$argv[1]}")) $code = file_get_contents(getcwd() . "/{$argv[1]}"); // ok, now its valid with some massaging
} else $code = stream_get_contents(STDIN); // no arguments we read stdin for the file contents

// get the git date
$date = shell_exec('git log --pretty=format:"%ad" -1');
$date = date('Y-m-d', strtotime($date));

// get the git tag as version with commit count (x.y.z-a)
$version = shell_exec('git describe');
$version = match ($version) {
    null => '0.0.0',
    false => '0.0.0',
    default => str_replace("\n", '', $version),
};
$version = implode('-', array_slice(explode('-', $version), 0, 2));

// version without commit count (x.y.z)
$ver = strstr($version, '-', true) ?: $version;

// apply the data and version
if (str_contains($code, '$Date$') || str_contains($code, '$Id$'))
    $code = str_replace(['$Date$', '$Id$'], ["\$Date: {$date}\$", "\$Id: {$version}\$"], $code);

// the ver
if (str_contains($code, ' * @version $version'))
	$code = str_replace(' * @version $version', " * @version $ver", $code);

echo $code;
