#!/usr/bin/env php
<?php

/**
 * Develop
 *
 * Tinkering development environment. Used to play with or try out stuff.
 *
 * PHP version 8.4
 *
 * @author Philip Michael Raab<philip@cathedral.co.za>
 * @package Develop\Tinker
 *
 * @license UNLICENSE
 * @license https://unlicense.org/UNLICENSE UNLICENSE
 *
 * @version $Id$
 * $Date$
 */

declare(strict_types= 1);

/**
 * git attribute tagger clean
 *
 * version 3
 *
 * added @version tagging
 */
if (count($argv) > 1) { // we have some command line arguments to deal with
    if (file_exists("{$argv[1]}")) $code = file_get_contents("{$argv[1]}"); // the first argument is a valid file
    else if (file_exists(getcwd() . "/{$argv[1]}")) $code = file_get_contents(getcwd() . "/{$argv[1]}"); // ok, now its valid with some massaging
} else $code = stream_get_contents(STDIN); // no arguments we read stdin for the file contents

// our regex pattern to match the $Date$ and $Id$ tags
$pattern = '/(\$(Date|Id))(: [a-zA-Z0-9 :+\.\-]+)(\$)/i';
$replacement = '$1$4';
// replace those tags
$code = preg_replace($pattern, $replacement, $code);

// our regex pattern to match the @version $version tag
$pattern = '/^( * @version )([0-9+\.?]+)(-[0-9]+)?$/i';
$replacement = '$1$version';
// replace that tag
$code = preg_replace($pattern, $replacement, $code);

echo $code;
