#!/usr/bin/env php
<?php
/**
 * version 2
 */
if (count($argv) > 1) {
    if (file_exists("{$argv[1]}")) $code = file_get_contents("{$argv[1]}");
    else if (file_exists(getcwd() . "/{$argv[1]}")) $code = file_get_contents(getcwd() . "/{$argv[1]}");
} else $code = stream_get_contents(STDIN);

$date = shell_exec('git log --pretty=format:"%ad" -1');
$date = date('Y-m-d', strtotime($date));

$version = shell_exec('git describe');
// $version = shell_exec('/usr/local/Cellar/git/2.37.0/libexec/git-core/git-describe');

$version = match ($version) {
    null => '0.0.0',
    false => '0.0.0',
    default => str_replace("\n", '', $version),
};

$version = implode('-', array_slice(explode('-', $version), 0, 2));
// $version = str_contains($version, '-') ? strstr($version, '-', true) : $version;

// function str_replace_once($search, $replace, $subject): string {
//     $pos = strpos($subject, $search);
//     if ($pos !== false)
//         $subject = substr_replace($subject, $replace, $pos, strlen($search));
//     return $subject;
// }
//
// $code = str_replace_once('$Date$', "\$Date: {$date}\$", $code);
// $code = str_replace_once('$Id$', "\$Id: {$version}\$", $code);

if (str_contains($code, '$Date$') || str_contains($code, '$Id$'))
    $code = str_replace(['$Date$', '$Id$'], ["\$Date: {$date}\$", "\$Id: {$version}\$"], $code);

echo $code;
